added conditional statements for calling first three operations and checking for certain errors conditions

diff --git a/matrix b/matrix
--- a/matrix
+++ b/matrix
@@ -3,6 +3,7 @@ printf "*************SHELL: $SHELL*************\n"
 #global variables
 numRows=0
 numCols=0
+filePath=tempFile$$
 
 # validateMatrix()
 # parameter(s): File containing matrix to be verified
@@ -36,17 +37,7 @@ validateMatrix(){
 #           - argument count is  > 1
 #           - file containing matrix cannot be read
 dims(){
-    #printf "dims called with arg: $1\n"
-    
-    while read numLine
-    do
-        for i in $numLine
-        do
-            numCols=$(expr $numCols + 1)
-        done
-    done <$1
-    numRows=$(wc -l <$1)
-    printf "$numRows $numCols\n"
+
 }
 
 # transpose()
@@ -101,5 +92,28 @@ add(){
 multiply(){
     printf "add called with arg1: $1, arg2: $2\n"
 }
-$1 ${@:2}
+
+#operation == dims or transpose or mean
+if [ $1 = "dims" ] || [ $1 = "transpose" ] || [ $1 = "mean" ]
+    then
+    echo -e "arg1: $1\targ2: $2\t argc: $#"
+    #if user tries to pass more than two args to the above three operations
+    if [ $# -gt 2 ]
+        #handle error
+        then
+        #error message redirected from stdout to stderr
+        echo -e "Error executing $1 - invalid number of arguments" 
+        exit 1
+    #three args total ($2 contains file name to be passed to operation) 
+    elif [ $# = 2 ]
+        then
+        $1 $2
+    #two args total => means no file name passed => which means read from stdin
+    else
+        cat > $filePath
+        $1 $tempFile$$
+    fi
+fi
+
+#$1 ${@:2}
 
